In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
df.shape

(50, 5)

In [6]:
df  = df.drop('State',axis=True)

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [ ]:
corr = df.corr()
sns.heatmap(corr,annot = True)

In [9]:
x = df.drop('Profit',axis=True)
y = df['Profit']

In [10]:
x.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [13]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((40, 3), (10, 3), (40,), (10,))

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [16]:
y_pred = lr.predict(x_test).round(1)
y_pred

array([103901.9, 132763.1, 133567.9,  72911.8, 179627.9, 115166.6,
        67113.6,  98154.8, 114756.1, 169064. ])

In [17]:
print("Training Accuracy :",lr.score(x_train,y_train))
print("Testing Accuracy :",lr.score(x_test,y_test))

Training Accuracy : 0.9499572530324031
Testing Accuracy : 0.9393955917820569


In [18]:
calculation = pd.DataFrame(np.c_[y_test,y_pred],columns=['Actual','Predict Salary'])
calculation.head()

Actual  Predict Salary
0  103282.38        103901.9
1  144259.40        132763.1
2  146121.95        133567.9
3   77798.83         72911.8
4  191050.39        179627.9

In [19]:
lr.intercept_

np.float64(42989.00816508665)

In [20]:
lr.coef_

array([0.77884104, 0.0293919 , 0.03471025])

In [21]:
feature = [1655349.20,136797.80,471784.10]
scale_feature = sc.transform([feature])
scale_feature

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[34.80624377,  0.55714752,  2.15394309]])

In [22]:
y_pred_test = lr.predict(scale_feature)
y_pred_test

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([43016.20783587])